### ISSUE TITLE
Helper

### ISSUE THREAD

**Issue by elarion83** [anouarcharif/CakePHP3-Media#2]
Salut Salut ! Dis-moi, j'ai une erreur pour le chargement du helper, cakephp ne me trouve pas le MediaHelper et me génère donc une erreur.. as-tu une idée d'ou cela peut provenir ?

Merci ! ^^

**Comment by anouarcharif** [comment]
Bonjour,

Normalement, si tu as suivi la documentation ... tu dois pas te retrouver avec cette erreur ... mais ceci dit tu peux vérifier ces points :

1- Vérifier si tu as bien le dossier Media dans .../src/plugins/
2- Si le Module est bien chargé.
3- Si le fichier MediaHelper.php dans .../src/plugins/Media/src/View/Helper/MediaHelper.php.
4- Tu fais comment pour la déclaration du Helper (public $helpers = ["Media.Media"];)?
5- Pour afficher ($this->Media->iframe ....)

Voilà ... tiens moi au courant ...

**Comment by elarion83** [comment]
Alors tous tes points sont bons ! A part le 4, disons que ca fait deux semaines que j'ai pas bossé sur le pret et cakephp je suis en train de l'apprendre, c'est dans le model que je doit déclarer le helper ? ou dans l'appcontroller ?

**Comment by anouarcharif** [comment]
C'est dans la partie Controller ...

**Comment by elarion83** [comment]
Pu**\* je t'aime ! 

Merci beaucoup pour ton efficacité, ton plugin, ta rapidité de réponse et tout le reste ! 

Encore merci beaucoup !

**Comment by anouarcharif** [comment]
Haha, content pour toi ... et merci d'avoir utilisé le plugin ... si tu as des remarques sur son sujet n'hésite pas à m'écrire.

Bonne chance.

**Comment by elarion83** [comment]
Au final le code génère quand même des erreurs : 

Strict (2048): Declaration of Media\Controller\MediasController::beforeFilter() should be compatible with Cake\Controller\Controller::beforeFilter(Cake\Event\Event $event) [ROOT/plugins/Media/src/Controller/MediasController.php, line 11]

Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in /plugins/Media/src/Controller/MediasController.php on line 29 and defined [CORE/src/Controller/Controller.php, line 724]

Strict (2048): Declaration of Media\Model\Table\MediasTable::initialize() should be compatible with Cake\ORM\Table::initialize(array $config) [ROOT/plugins/Media/src/Model/Table/MediasTable.php, line 12]

Deprecated (16384): Controller::$layout is deprecated. Use $this->viewBuilder()->layout() instead. [CORE/src/Controller/Controller.php, line 375]

**Comment by anouarcharif** [comment]
Bonjour,

C'est bug ne sont pas méchant ... mais puisque tu utilises le mode strict de PHP:

Voilà ce qu'il faut faire:

1 - Dans [ROOT/plugins/Media/src/Model/Table/MediasTable.php, modifie ça initialize($config = array()) par ça initialize(array $config)

2- Dans /plugins/Media/src/Controller/MediasController.php remplace ça function beforeFilter() par public function beforeFilter(Event $event) et beforeRender() par beforeRender(Event $event)

3- pour ça (pas de relation avec mon plugin) 

Deprecated (16384): Controller::$layout is deprecated. Use $this->viewBuilder()->layout() instead. [CORE/src/Controller/Controller.php, line 375]

Faut juste remplacer $this->layout = 'layout' par $this->viewBuilder()->layout('layout'); (Les nouveautés de CakePHP3)

Voilà

**Comment by elarion83** [comment]
OKay pour le 1 et 2, le 3 je verrai ca de mon côté, par contre a aucun moment j'ai  $this->layout = 'layout' dans mes controller... :/

**Comment by elarion83** [comment]
Donc dans le media controller de ton plugin j'"ai remplacé tous les  $this->layout = 'layout' par $this->viewBuilder()->layout('layout'); et j'ai une nouvelle erreur : 

Call to a member function read() on a non-object

Je pense avoir mal fait la non ?

**Comment by anouarcharif** [comment]
Bonjour,

Il faut remplacer 'layout' par ce que t'avais déja dans $this->layout = 'layout';

Pour Call to a member function read() on a non-object ... est ce que je peux avoir l'erreur complet histoire de savoir la ligne exacte ...

**Comment by elarion83** [comment]
Salut ! Oui c'est ce que j'avais fait, donc pour le read() l'erreur qui est générée est la suivante : 

Error: Call to a member function read() on a non-object 
File /src/Controller/AppController.php 
Line: 96

J'ai donc remplacé  :   $id = $this->Session->read('Auth.User.id') 
par :  $id = $this->Auth->user('id')

et je me trouve par la suite devant une erreur read() une nouvelle fois mais sur la lecture du rôle, vu que j'en ai pas J'ai donc commenté :  return $this->Session->read('Auth.User.role') == 'admin'; 

Et je me retrouve devant une erreur forbidden

**Comment by anouarcharif** [comment]
Bonjour,

Est ce que tu as bien chargé le composant Session ?

**Comment by elarion83** [comment]
Hmmm je ne crois pas ^^ Tu aurais un lien ? La doc de cakephp est très floue et très incomplète je trouve :/

**Comment by anouarcharif** [comment]
Bonjour,

C'est un problème lié au composant Session qui n'est pas chargé ... d'oû l'erreur Read ...

http://book.cakephp.org/3.0/fr/development/sessions.html

**Comment by elarion83** [comment]
Tu n'aurais pas un autre lien ? A aucun moment ils expliquent comment la mettre en place d'une façon claire.. tu va avoir l'impression que je fais pas d'effort mais cette doc je l'ai lue et relue et franchement..

**Comment by anouarcharif** [comment]
Bonjour,

Dans ton controller essaye de faire ça :

Tu peux soit rajouter ça dans la function initialize () 
$this->Session = $this->request->session ... donc tu dois déclarer Session comme attribut public.

Ou remplacer directement $this->Session->read par $this->request->session()->read();

**Comment by anouarcharif** [comment]
Et c'est de ma faute ... je dois préciser dans la documentation que c'est $this->request->session()->read(); et non $this->Session->read ...

**Comment by anouarcharif** [comment]
Bonjour,

Voilà un petit extrait de la documentation :

la session est accessible via:
- Controllers
- Views
- Helpers
- Cells
- Components
  En plus de l’objet basique session, vous pouvez aussi utiliser Cake\View\Helper\SessionHelper pour interagir avec la session dans vos views. Un exemple simple de l’utilisation de session serait:

$name = $this->request->session()->read('User.name');

// Si vous accédez à la session plusieurs fois,
// vous voudrez probablement une variable locale.
$session = $this->request->session();
$name = $session->read('User.name');

**Comment by elarion83** [comment]
J'ai remplacé les $this->Session()->read en $this->request->Session()->read et commenté la ligne d'admin, cependant une erreur persiste : 

Forbidden

Warning (4096): Argument 1 passed to Cake\Controller\Controller::beforeFilter() must be an instance of Cake\Event\Event, none given, called in /home/ngdesigne/www/creaweb/ublane/plugins/Media/src/Controller/MediasController.php on line 29 and defined in [/home/ngdesigne/www/creaweb/ublane/vendor/cakephp/cakephp/src/Controller/Controller.php, line 724] 

c'est toujours en rapport avec la session .. ?

**Comment by anouarcharif** [comment]
Bonjour,

Non je t'avais demandé hier de vérifier beforeFilter() pour mettre 

public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);

**Comment by anouarcharif** [comment]
Et faut pas commenter la ligne ... faut retourner true déja pour tester sinon forbidden veut dire accès interdit ...

**Comment by elarion83** [comment]
Toute mes excuses je n'avai pas vu le 

parent::beforeFilter($event);

Maintenant que c'est à la ligne 46 du mediacontroller que j'ai une erreur : 

Error: Call to a member function Behaviors() on a non-object 
File /home/ngdesigne/www/creaweb/ublane/plugins/Media/src/Controller/MediasController.php 
Line: 46

ca correspond à : 
        if(!in_array('Media', $this->$ref->Behaviors()->loaded())){
            return $this->render('nobehavior');
        }

Et oui j'ai commenté mais rajouté un return null; en dessous.

**Comment by anouarcharif** [comment]
$ref vaut quoi ?

**Comment by elarion83** [comment]
Comment je peux faire pour vérifier sa valeur ? un return $ref; dans le controller ?

**Comment by anouarcharif** [comment]
$ref c'est ton modél ... vérifie si tu as bien $this->loadModel($ref); avant cette ligne ...

Oui tu peux vérifier dans le controller du plugin avec un exit; juste après ...

**Comment by anouarcharif** [comment]
Mais normalement ça doit être déjâ le model avec qui tu veux attacher le plugin ...

**Comment by anouarcharif** [comment]
Par exemple je veux gérer les images de mon articles je vais mettre dans l'iframe ..../Articles/{id} à noté que si tu n'as pas récupérer la dernière version du plugin tu dois mettre Article sans "s"

**Comment by elarion83** [comment]
J'ai ceci dans mon media controller : $this->loadModel("Media.Medias"); Mais ce n'est pas dans la même fonction que le problème du behaviour.

Et je l'utilise pour User ton plugin, ce qui me donne : 

```
        // MODEL en singulier
        echo $this->Media->iframe('User',h($user->id));
```

vu que j'utilise la dernière version

**Comment by anouarcharif** [comment]
Tu as attaché le Behavior à ton model ? par exemple ...

public function initialize(array $config)
    {
        $this->addBehavior(
            'Media.Media', [
                'path' => 'img/upload/%y/%m/%f',  
                'extensions' => ['jpg', 'png'],  
                'limit' => 0,  
                'max_width' => 0,  
                'max_height' => 0,  
                'size' => 0  
            ]
        );
    }

**Comment by anouarcharif** [comment]
J'avais procédé à quelques modifications hier ... du coup la nouvelle version utilise le model en pluriel pour ne plus avoir recours à pluralize et singularize ... :dancer:

**Comment by elarion83** [comment]
Oui oui j'ai bien attaché le behavior au model en suivant le tuto ;)

Et que ce soit au plurier ou au singulier j'ai toujours le même problème du behavior..

**Comment by anouarcharif** [comment]
Si tu as attaché le Behavior je ne vois pas pourquoi tu as ce problème ... ceci dit qu'il y a un problème avec ta UsersTable.php

**Comment by anouarcharif** [comment]
Sinon je sais pas si je peux jeter un coup d'oeil sur ton code ... pour voir ce qui cloche  ...

**Comment by elarion83** [comment]
J'ai juste la fonction initialize dans laquelle j'integre, j'attache, mes relations, le behavior media, la fonction qui me permet de valider mes champs lors de l'ajout ou de la modification, rien d'autre :/

**Comment by elarion83** [comment]
Oui oui aucun soucis, tu veux faire ca comment ?

**Comment by anouarcharif** [comment]
Tu peux m'ecrire ici ... anouarcharif[@]gmail.com ... je supprime ce commentaire ... juste après la reception de ton mail ...

**Comment by anouarcharif** [comment]
Le problème a été réglé ...
